-- ==============================================================================
-- SIH26054 Digital Twin - Supabase PostgreSQL Schema
-- Aerospace UAV Health Monitoring & FMEA Incident Persistence
-- ==============================================================================

-- 1. Flights Master Table
CREATE TABLE IF NOT EXISTS public.flights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    flight_id TEXT UNIQUE NOT NULL,
    profile TEXT NOT NULL DEFAULT 'patrol',
    duration_s NUMERIC(10, 2) NOT NULL DEFAULT 600.0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL
);

-- 2. Telemetry Records (15-Channel Time-Series Log)
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id TEXT NOT NULL REFERENCES public.flights(flight_id) ON DELETE CASCADE,
    timestamp_s NUMERIC(10, 3) NOT NULL,
    rpm NUMERIC(8, 2) NOT NULL,
    health_score NUMERIC(5, 2) NOT NULL DEFAULT 96.0,
    stage1_anomaly BOOLEAN DEFAULT false NOT NULL,
    stage2_fault TEXT DEFAULT 'normal' NOT NULL,
    channels JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_telemetry_flight_time 
ON public.telemetry_logs (flight_id, timestamp_s);

-- 3. FMEA Diagnostic Alerts & Copilot Reports
CREATE TABLE IF NOT EXISTS public.alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    alert_id TEXT UNIQUE NOT NULL,
    flight_id TEXT NOT NULL REFERENCES public.flights(flight_id) ON DELETE CASCADE,
    timestamp_s NUMERIC(10, 3) NOT NULL,
    fault_type TEXT NOT NULL,
    confidence NUMERIC(5, 4) NOT NULL,
    severity TEXT NOT NULL,
    auto_action_eligible BOOLEAN DEFAULT false NOT NULL,
    key_sensors TEXT[] DEFAULT '{}'::TEXT[],
    report_text TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_alerts_flight 
ON public.alerts (flight_id, created_at DESC);

-- 4. Fleet Federated Learning Global Aggregation Rounds
CREATE TABLE IF NOT EXISTS public.fleet_rounds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    round_num INTEGER UNIQUE NOT NULL,
    num_clients INTEGER NOT NULL DEFAULT 6,
    global_f1 NUMERIC(5, 4) NOT NULL,
    summary JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.flights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fleet_rounds ENABLE ROW LEVEL SECURITY;

-- Allow anonymous and authenticated read/write access for SIH telemetry
CREATE POLICY "Public full access flights" ON public.flights FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access telemetry_logs" ON public.telemetry_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access alerts" ON public.alerts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access fleet_rounds" ON public.fleet_rounds FOR ALL USING (true) WITH CHECK (true);
